//
//  File.swift
//  IgniteStarter
//
//  Created by Justin Purnell on 12/11/24.
//

import Foundation

enum skillTypes: String, Codable {
	case agile = "Agile Methodologies"
	case analytics = "Analytics"
	case businessAnalysis = "Business Analysis"
	case operations = "Company Operations"
	case strategyContent = "Content Strategy"
	case financeCorporate = "Corporate Finance"
	case strategyCorporate = "Corporate Strategy"
	case strategyFormulation = "Corporate Strategy Formulation"
	case leadershipCrossFunctionalTeam = "Cross-functional Team Leadership"
	case dataAnalytics = "Data Analysis"
	case dataScience = "Data Science"
	case digitalMedia = "Digital Media"
	case strategyDigital = "Digital Strategy"
	case dueDiligence = "Due Diligence"
	case entrepreneurship = "Entrepreneurship"
	case execVisibility = "Executive Visibility"
	case finance = "Finance"
	case financialAnalysis = "Financial Analysis"
	case financialModeling = "Financial Modeling"
	case leadership = "Leadership"
	case management = "Management"
	case consultingManagement = "Management Consulting"
	case marketPlanning = "Market Planning"
	case marketResearch = "Market Research"
	case strategyMarketing = "Marketing Strategy"
	case msftXLS = "Microsoft Excel"
	case msftPPT = "Microsoft PowerPoint"
	case msftDOC = "Microsoft Word"
	case newMedia = "New Media"
	case newVentureDevelopment = "New Venture Development"
	case personalization = "Personalization"
	case presentations = "Presentations"
	case problemSolving = "Problem Solving"
	case processImprovement = "Process Improvement"
	case productDevelopment = "Product Development"
	case productLeadership = "Product Leadership"
	case productManagement = "Product Management"
	case projectManagement = "Project Management"
	case publicSpeaking = "Public Speaking"
	case ratioAnalysis = "Ratio Analysis"
	case research = "Research"
	case socialInfluence = "Social Influence"
	case socialMedia = "Social Media"
	case stakeholderManagement = "Stakeholder Management"
	case strategicPlanning = "Strategic Planning"
	case strategicVision = "Strategic Vision"
	case strategy = "Strategy"
	case swift = "Swift"
	case technicalProductManagement = "Technical Product Management"
	case ventureCapital = "Venture Capital"
	case spanish = "Spanish"
	case swiftui = "SwiftUI"
	case xcode = "Xcode"
	case macos = "macOS"
	case windows = "Windows"
	case unix = "Unix/Linux"
	case keynote = "Keynote"
	case bloomberg = "Bloomberg Terminal"
	case spss = "SPSS"
	case photoshop = "Photoshop"
	case finalCut = "Final Cut"
	case html = "HTML"
	case css = "CSS"
}
